//
//  TransactionSigningTests.swift
//  ZilliqaSDK
//
//  Created by Alexander Cyon on 2018-09-11.
//  Copyright © 2018 Open Zesame. All rights reserved.
//

import XCTest
@testable import ZilliqaSDK


class TransactionSigningTests: XCTestCase {
    func testFoo() {
        XCTAssertTrue(true)
    }

    func testTransactionSigning() {

        // Some uninteresting Zilliqa TESTNET private key, containing worthless TEST tokens.
        let privateKey = "0E891B9DFF485000C7D1DC22ECF3A583CC50328684321D61947A86E57CF6C638"
        let wallet = Wallet(privateKeyHex: privateKey, nonce: 0)!

        XCTAssertEqual(wallet.keyPair.publicKey.hex.compressed.lowercased(), "034ae47910d58b9bde819c3cffa8de4441955508db00aa2540db8e6bf6e99abc1b")


        let service = DefaultZilliqaService(wallet: wallet)
        let recipient = Recipient(string: "9CA91EB535FB92FDA5094110FDAEB752EDB9B039")!

        let payment = Payment(
            to: recipient,
            amount: 15,
            gasLimit: 1,
            gasPrice: 1,
            from: wallet
        )!

        let unsignedTx = UnsignedTransaction(payment: payment, version: 0)


        XCTAssertEqual(unsignedTx.amount, 15)
        XCTAssertEqual(unsignedTx.gasLimit, 1)
        XCTAssertEqual(unsignedTx.gasPrice, 1)
        XCTAssertEqual(unsignedTx.nonce, 1)
        XCTAssertEqual(unsignedTx.version, 0)
        XCTAssertEqual(unsignedTx.to, "9CA91EB535FB92FDA5094110FDAEB752EDB9B039")


        let message = messageFromUnsignedTransaction(unsignedTx, publicKey: wallet.keyPair.publicKey)

        XCTAssertEqual(message.description, "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000019CA91EB535FB92FDA5094110FDAEB752EDB9B039034ae47910d58b9bde819c3cffa8de4441955508db00aa2540db8e6bf6e99abc1b000000000000000000000000000000000000000000000000000000000000000f000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000")

        let signature = service.sign(message: message, using: wallet.keyPair)

        // Generated by createhttps://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/3a4566138def7d622b0bbc331186ce7d2b8c465c
        let expectedSignature = "58a1d11298c80452b91ab3e562bc7160bea8dd49a877885d48a17f3ad4d886d6b94a4413a88630686068485588e80a4cae088fa330ed6a657cf134907157aa64"

        XCTAssertEqual(signature.asHexString(), expectedSignature)

    }
}
