env:
  global:
    - LC_CTYPE=en_US.UTF-8
    
branches:
  only:
    - master

matrix:
  include:
    - os: linux
      language: generic
      env:
        - JOB=Linux
        - SWIFT_VERSION=5.0
      script:
        - swift --version
        - swift build
        - swift test
      sudo: required
      dist: trusty
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

notifications:
  email: false
