language: objective-c

os:
    - linux
    - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9.3

env:
  - DANGER=1
  - TEST=iOS
  - TEST=Unix
  - TEST=watchOS
  - TEST=tvOS
  - TEST=iOS-Example
  - TEST=SPM
matrix:
    exclude:
      - os: osx
        env: DANGER=1

      - os: linux
        env: TEST=iOS

      - os: linux
        env: TEST=watchOS

      - os: linux
        env: TEST=tvOS

      - os: linux
        env: TEST=iOS-Example

    include:
      - osx_image: xcode9.4
        os: osx
        env: TEST=iOS

      - osx_image: xcode10.2
        os: osx
        env: TEST=iOS

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxSwift SWIFT_VERSION=4 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxCocoa SWIFT_VERSION=4 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxBlocking SWIFT_VERSION=4 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxTest SWIFT_VERSION=4 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxSwift SWIFT_VERSION=4.2 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxCocoa SWIFT_VERSION=4.2 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxBlocking SWIFT_VERSION=4.2 ./scripts/validate-podspec.sh"

      - osx_image: xcode10
        os: osx
        env: BUILD="TARGET=RxTest SWIFT_VERSION=4.2 ./scripts/validate-podspec.sh"


notifications:
  slack: rxswift:3ykt2Z61f8GkdvhCZTYPduOL
  email: false

install:
  - if [ `uname` == "Linux" ] ; then
        eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)";
    fi

script:
  - if [[ `uname` == "Linux" ]] ; then
        swiftenv install swift-4.2 || true;
    fi
  - if [[ `uname` == "Unix" ]] ; then
        brew install swiftlint || true;
    fi
  -
    if [[ ! -z "${BUILD}" ]] ; then
      eval "TRAVIS=1 ${BUILD}";
    else
      if [[ "${DANGER}" -eq 1 ]] ; then
        bundle install --path vendor/bundle;
        bundle exec danger --verbose;
      else
        if [[ `uname` == "Darwin" ]] ; then
          xcodebuild -version;
          xcodebuild -showsdks;
        fi;
        swift --version;
        TRAVIS=1 ./scripts/all-tests.sh "${TEST}";
      fi;
    fi;

after_success:
  - sleep 5 # workaround https://github.com/travis-ci/travis-ci/issues/4725
